---
# Source: ingressmonitorcontroller/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingressmonitorcontroller-role-binding
roleRef:
  kind: ClusterRole
  name: ingressmonitorcontroller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
  namespace: monitoring
